### ISSUE TITLE
 Z-index issue with the iphone6 image.

### ISSUE THREAD

**Issue by Vasant18** [Vasant18/Z-index#3]
I want the features seection of my webpage to ovelap a bit on the home page so that the iphone image looks like it has been cut a little bit from the bottom. Below is the screenshot from the code.You can see that I have commented out the z-index styling, when I apply this styling the iphone image gets bigger and gets out of the flow.

https://github.com/Vasant18/Z-index/tree/main/Issue%20Screenshots

**Comment by MohammedGayaz** [comment]
the image is getting scaled because when u make it position absolute it gets scaled 60% with respect to the screen, so it gets bigger. to change the 60% to 300px. and make the below section position relative.

this might help:

/* Title Image */
.title-image {
    width: 300px;
    transform: rotate(25deg);
    position: absolute;
}

/* feature section */

#features {
    padding: 7% 15%;
    background-color: #fff;
    position: relative;
}
